#!/usr/bin/env sh

export jar_vers="0.1.0"
export jar_name="fuzzy-ada"
export maven_repository="http://gatekeeper.wilsley.xyz/maven/ai-models"

export project_tag="ada"
export project_name="adaadherence" # avoid dashed
export ez_namespace="development"
export model_id="ada-adherence-model"
export model_desc="ADA Adherence Model"
export deploym_desc="ADA Adherence Model Cluster"
export marker="AdaAdherenceBundle"