#!/usr/bin/env sh

export jar_vers="0.2.2"
export jar_name="fuzzy-who"
export maven_repository="http://gatekeeper.wilsley.xyz/maven/ai-models"

export project_tag="who"
export project_name="whoadherence" # avoid dashed
export ez_namespace="development"
export model_id="who-adherence-model"
export model_desc="WHO Adherence Model"
export deploym_desc="WHO Adherence Model Cluster"
export marker="WhoAdherenceBundle"